.PHONY: all

PYTHON ?= python3

all: Keymaps/Default.sublime-keymap

Keymaps/Default.sublime-keymap: Keymaps/translate_keys.py Keymaps/Default.json Keymaps/Custom.json
	{ echo '//Autogenerated, do not edit.' && \
		$(PYTHON) $^ | head -n-1 && \
		tail -n+2 Keymaps/Custom.json; } > $@
